site_name: VideoGrace Server
site_url: https://videograce.ru
theme:
  name: material
  custom_dir: overrides

plugins:
  - with-pdf:
      author: v 1.0.240218
      copyright: (C) ООО "ИВС", 2024
    
      cover: true
      cover_title: VideoGrace Server
      cover_subtitle: Руководство администратора

nav:
  - Домашняя: 'index.md'
  - Полезные сведения:
    - Виды систем видеоконференцсвязи: 'helpful/vcs_types.md'
  - Установка:
    - Установка на Windows: 'install/win.md'
    - Установка на Linux: 'install/lin.md'
    - Первоначальная настройка: 'install/first_steps.md'
  - Начало работы:
    - Обеспечение доступа: 'setup/accessibility.md'
    - Подключение пользователей: 'setup/client_connect.md'
  - Система:
    - Управление системой: 'system/managing.md'      
    - Пользователи и группы: 'system/clients_groups.md'
    - Конференции: 'system/conferences.md'
    - Сеть: 'system/network.md'
    - Настройки: 'system/settings.md'
    - Нагрузочное тестирование: 'system/load_testing.md'
  - API:
    - REST: 'api/rest.md'
  - Технические требования:
    - Технические характеристики: 'requirements/tech_spec.md'
    - Требования к сети: 'requirements/network.md'
    - Клиентское рабочее место: 'requirements/client.md'
    - Серверное оборудование: 'requirements/server.md'
    - Камеры и экраны: 'requirements/camera.md'
    - Звуковое оборудование: 'requirements/sound.md'
  - О системе:
    - Версия: 'about/version.md'
    - Лицензия: 'about/license.md'
    - Компания разработчик: 'about/company.md'
    - Контакты: 'about/contacts.md'
