site_name: VideoGrace SDK
site_url: https://videograce.ru
theme:
  name: material
  custom_dir: overrides

#plugins:
#  - with-pdf:
#      author: v 1.0.24313
#      copyright: (C) ООО "ИВС", 2024
    
#      cover: true
#      cover_title: VideoGrace SDK
#      cover_subtitle: Руководство разработчика

nav:
  - Домашняя: 'index.md'
  - Общие сведения:
    - Тракт дуплексной аудиосвязи: 'helpful/sound_path.md'
  - Установка:
    - Получение и сборка на Windows: 'install/win.md'
    - Получение и сборка на Linux: 'install/lin.md'
    - Тестовая сеть: 'install/test_net.md'
  - Основные операции:
    - Авторизация: 'base/auth.md'
    - Работа со списком контактов: 'base/contacts.md'
    - Работа со списком конференций: 'base/conferences.md'
    - Создание / редактирование конференции: 'base/conference_manage.md'
    - Отправка текстовых сообщений: 'base/im.md'
    - Подключение к конференции: 'base/connect_to_conf.md'
    - Подключение AV устройств: 'base/connect_av.md'
    - Рендеринг видео и звука: 'base/rendering.md'
    - Звонок абоненту: 'base/call.md'
  - Оборудование:
    - Камера: 'dev/camera.md'
    - Захват окна/экрана: 'dev/screen_capt.md'
    - Микрофон: 'dev/microphone.md'
    - Вывод звука: 'dev/sound.md'
    - Монитор: 'dev/monitor.md'
  - WebSocket Client Protocol:
    - Основные принципы: 'wcp/base.md'
    - Команды: 'wcp/commands.md'
  - REST API:
    - Основные принципы: 'rest/base.md'
    - Команды: 'rest/commands.md'
  - О системе:
    - Версия: 'about/version.md'
    - Лицензия: 'about/license.md'
    - Компания разработчик: 'about/company.md'
    - Контакты: 'about/contacts.md'
