site_name: VideoGrace Client
site_url: https://videograce.ru
theme:
  name: material
  custom_dir: overrides

plugins:
  - with-pdf:
      author: v 1.0.24318
      copyright: (C) ООО "ИВС", 2024
    
      cover: true
      cover_title: VideoGrace Client
      cover_subtitle: Руководство пользователя

nav:
  - Домашняя: 'index.md'
  - Установка:
    - Установка на Windows: 'install/win.md'
    - Установка на Linux: 'install/lin.md'
  - Начало работы:
    - Подключение к серверу: 'setup/connect.md'
    - Добавление контактов: 'setup/contacts.md'
    - Создание конференций: 'setup/conference.md'
  - Проведение конференций:
    - Старт конференции: 'conferencing/start.md'
    - Демонстрация экрана / удаленное управление: 'conferencing/demonstration.md'
    - Управление участниками: 'conferencing/moderation.md'
    - Завершение конференции: 'conferencing/end.md' 
  - Настройки:
    - Настройка камеры: 'settings/camera.md'
    - Настройка звука: 'settings/sound.md'
    - Настройки сети: 'settings/network.md'
    - Настройки приложения: 'settings/app.md'
    - Настройки записи: 'settings/record.md'
    - Настройки антивируса: 'settings/antivir.md'
  - О системе:
    - Версия: 'about/version.md'
    - Лицензия: 'about/license.md'
    - Компания разработчик: 'about/company.md'
    - Контакты: 'about/contacts.md'
