site_name: VideoGrace Client

#plugins:
#  - with-pdf:
#      author: WHO
#      copyright: ANY TEXT
    
#      cover: false
#      back_cover: true
#      cover_title: TITLE TEXT
#      cover_subtitle: SUBTITLE TEXT
#      custom_template_path: TEMPLATES PATH
    
#      toc_title: TOC TITLE TEXT
#      heading_shift: false
#      toc_level: 3
#      ordered_chapter_level: 2
    
#      render_js: true
      #headless_chrome_path: headless-chromium
    
#      output_path: any-place/document.pdf
#      enabled_if_env: ENABLE_PDF_EXPORT
    
#      debug_html: true
#      show_anchors: true
#      verbose: true      

nav:
  - Домашняя: 'index.md'
  - Установка:
    - Установка на Windows: 'install/win.md'
    - Установка на Linux: 'install/lin.md'
  - Начало работы:
    - Подключение к серверу: 'setup/connect.md'
    - Добавление контактов: 'setup/contacts.md'
    - Создание конференций: 'setup/conference.md'
  - Настройки:
    - Настройка камеры: 'settings/camera.md'
    - Настройка звука: 'settings/sound.md'
    - Настройки сети: 'settings/network.md'
    - Настройки приложения: 'settings/app.md'
    - Настройки записи: 'settings/record.md'
  - Проведение конференций:
    - Старт конференции: 'conferencing/start.md'
    - Демонстрация экрана / удаленное управление: 'conferencing/demonstration.md'
    - Управление участниками: 'conferencing/moderation.md'
    - Завершение конференции: 'conferencing/end.md' 
  - О системе:
    - Версия: 'about/version.md'
    - Лицензия: 'about/licence.md'
    - Компания разработчик: 'about/company.md'
    - Контакты: 'about/contacts.md'
